# Generated by Django 5.2.5 on 2025-08-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('anio', models.CharField(max_length=40)),
                ('elenco', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=40)),
            ],
        ),
    ]
